language: node_js
node_js:
  - "12.13"
cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm run build
  
deploy:
  provider: npm
  email: "$NPM_EMAIL_ADDRESS"
  api_key: "$NPM_AUTH_TOKEN"
  skip-cleanup: true
  on:
    branch: release
